version: '3'

services:
    wiremock:
        container_name: local-wiremock
        build: .
        command: --port 7070 --extensions WiremockProxyTransformer
        ports:
            - '7070:7070'
        volumes:
            - ./stubs:/home/wiremock
